## 1.What does Pandas stand for?
- Panel Data — it's used for data analysis in Python.
## 2.What are the 2 collections used in Pandas?
- Series
- Dataframe
## 3.Name 4 things Pandas can do for us.
- Clean data
- Sort and filter
- Merge tables
- Analyze and summarize
## 4.To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- *inplace=True*
## 5.What is a CSV?
- A Comma-Separated Values file — stores table data as plain text.
## 6.When cleaning data what values do we not like in our data?
- Missing values
- Duplicates
- Outliers
- Wrong formats

In [2]:
#7.Import NumPy, create an array with a shape of (2, 3, 2).
import numpy as np
arr1 =np.arange(12)
print ("array is:",arr1)
#Reshape it into an array with shape (2, 3, 2).
reshapedArray = arr1.reshape((2,3,2))
print("The Reshaped array is:\n",reshapedArray)


array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]
The Reshaped array is:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [25]:
#8.Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20.
import numpy as np
arr = np.linspace(0,20,num = 6)
print ("Linearly spaced array:",arr)
#9.Make a Deep Copy of the above array
deepcopy_arr = arr.copy()
print("Deepcopy array:",deepcopy_arr)


Linearly spaced array: [ 0.  4.  8. 12. 16. 20.]
Deepcopy array: [ 0.  4.  8. 12. 16. 20.]


In [2]:
#10.Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11,12]])
#concatenating 3 arrays row wise vertically(axis=0)
newArray = np.concat((array1,array2,array3),axis=0)
print ("New concated array is:\n",newArray)
#11.Sort 'newArray' in order into 'sortedArray'
sotedArray=np.sort(newArray,axis=None)
print("sorted array is:",sotedArray)

New concated array is:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
sorted array is: [ 2  4  5  6  7 11 11 12 13 16 25 81]


In [3]:
#12.Unpack the array tuples from the above 'reshapedArray' into 4 well named variables.
import numpy as np

# Create and reshape the array
arr1 = np.arange(12)
reshapedArray = arr1.reshape(2, 3, 2)
print("The Reshaped array is:\n",reshapedArray)

# Unpack 4 row tuples from the reshaped array
first_row_block1 = reshapedArray[0][0] # block1 row1 of reshapearr [0 1]
second_row_block1 = reshapedArray[0][1] # block1 row2 of reshapearr [2 3]
first_row_block2= reshapedArray[1][0] # block2 row1 of reshapearr [6 7]
second_row_block2 = reshapedArray[1][1] # block2 row2 of reshapearr [8 9]
# Print the variables
print("First row of Block 1:", first_row_block1)
print("Second row of Block 1:", second_row_block1)
print("First row of Block 2:", first_row_block2)
print("Second row of Block 2:", second_row_block2)




The Reshaped array is:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
First row of Block 1: [0 1]
Second row of Block 1: [2 3]
First row of Block 2: [6 7]
Second row of Block 2: [8 9]


In [25]:
# 13. Combined and sort the arrays into one called 'comboArray' ...
import numpy as np
one =np.array([10,11,12,13,14,15,16,17])
two =np.array([20, 21, 22, 23, 24, 25, 26, 27])
three =np.array([ 0, 1, 2, 3, 4, 5, 6, 7])
# Combine and sort
comboArray = np.concatenate((one,two,three))
comboArray.sort()
# print the sorted array
print("The sorted array is:\n",comboArray)



The sorted array is:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [26]:
#14.Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
sec1 = comboArray[1]
print("sec1 is:",sec1)

# print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[2:]
print("sec2 is:",sec2)

# print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[3:14]
print("sec3 is:",sec3)

# print sec4 - the last 6 elements
sec4 = comboArray[-6:]
print("sec4 is:",sec4)

# print sec5 - all element from #0 up to and including #15, using the negative number method
sec5 = comboArray[-24:-8]
print("sec5 is:",sec5)

#print sec6 - from #20 every even element to the end
sec6 = comboArray[20::2]
print("sec6 is:", sec6)

# print sec7 - from the last element moving forward, every 5th element.
sec7 = comboArray[-1::-5]
print("sec7 is:",sec7)


sec1 is: 1
sec2 is: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3 is: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4 is: [22 23 24 25 26 27]
sec5 is: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
sec6 is: [24 26]
sec7 is: [27 22 15 10  3]


In [7]:
#15. Using Series, create a DataFrame
import pandas as pd
dinner_series = pd.Series({'Flour':'4 cups',
                           'Milk':'1 cup',
                           'Eggs':'2 large',
                           'Spam':'1 can'},
                           name='Dinner')
# convert series to Dataframe
df = pd.DataFrame(dinner_series)
print(df)
print(df.dtypes)

        Dinner
Flour   4 cups
Milk     1 cup
Eggs   2 large
Spam     1 can
Dinner    object
dtype: object


In [27]:
#16.Take this data and create a DataFrame named studentData
import pandas as pd

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']

         }
studentData = pd.DataFrame(data)
print(studentData)



      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [ ]:
# 17. Add a new column to the DataFrame
studentData["deserts"]=["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
print(studentData)



      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [33]:
#18.Sort the 'studentData' DataFrame in Ascending order 
#Sorting by column 'Name' and then "address"
studentData = studentData.sort_values(by=['Name', 'address'], ascending=[True, True])
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [37]:
#19.Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

import pandas as pd

# Create the DataFrame
df = pd.DataFrame({
    'Cows': [12, 20],
    'Goats': [22, 19]
}, index=['Year 1', 'Year 2'])

# Save the DataFrame to a CSV file
df.to_csv('cows_and_goats.csv')

In [51]:
#20.(A) Using Pandas, make your own .CSV file with data on vegetables 
import pandas as pd
vegetables = {'name':['carrot','cabbage','spinach','tomato'],
              'colour':['orange','green','green','red'],
              'price_per_lb':[5,4,10,8],
              }
df = pd.DataFrame(vegetables)
print(df)
df.to_csv('vegitables.csv')

 

      name  colour  price_per_lb
0   carrot  orange             5
1  cabbage   green             4
2  spinach   green            10
3   tomato     red             8


In [ ]:
#  (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
# Read the original CSV
df = pd.read_csv('vegitables.csv')

# Add a new column
df['Eaten_Raw'] = [True,False,False,True]

# Save the modified DataFrame to a new CSV file
df.to_csv('vegetables_updated.csv')
print(df)




   Unnamed: 0     name  colour  price_per_lb  Eaten_Raw
0           0   carrot  orange             5       True
1           1  cabbage   green             4      False
2           2  spinach   green            10      False
3           3   tomato     red             8       True
